import Head  from "next/head";
import Footer from "../../navigation/Footer";
import NavBar from "../../navigation/NavBar";
import SideBar from "../../navigation/SideBar";

export default function AdminLayout({ children }: { children?: JSX.Element }){
     return (
        <div className="grid lg:min-h-screen grid-rows-header  ">
            <NavBar />
            <div className="grid md:grid-cols-sidebar ">
                <SideBar />
                <div
                    className=" min-h-screen px-10 py-5"
                >
                    <main>
                        <Head>
                            <title>MTU MEMO</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/logo.ico" />
                        </Head>

                        {children}
                    </main>

                </div>

            </div>
            <Footer />
        </div>
    );
}