import Head from "next/head";
import Footer from "../../navigation/Footer";
import NavBar from "../../navigation/NavBar";
import SideBar from "../../navigation/SideBar";
import { useRouter } from "next/router";
import { hasCookie } from "cookies-next";
import { useEffect } from "react";
import AdminSideBar from "../../navigation/Admin/AdminSide";

export default function AdminLayout({ children }: { children?: JSX.Element }) {

    const router = useRouter()


    function checkUser() {
        const userCheck = hasCookie("AdminUser")

        console.log(userCheck)

        if (userCheck == false) {
            router.push("/")
        }
    }



    useEffect(() => {
        checkUser()
    }, [])

    return (
        <div className="grid lg:min-h-screen grid-rows-header  ">
            <NavBar />
            <div className="grid md:grid-cols-sidebar ">
                <AdminSideBar />
                <div
                    className=" min-h-screen px-10 py-5"
                >
                    <main>
                        <Head>
                            <title>MTU MEMO</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/logo.ico" />
                        </Head>

                        {children}
                    </main>

                </div>

            </div>
            <Footer />
        </div>
    );
}