import Head from "next/head";
import Footer from "../navigation/Footer";




export default function DefaultLayout({ children }: { children?: JSX.Element }) {

    return (
        <div>
            <div className="md:space-y-20  min-h-screen">
                {/* <EmpNav/> */}
                <div className="bg max-w-full mx-auto py-5 px-10 md:py-10 md:px-20 min-h-screen md:min-h-0">
                    <main>
                        <Head>
                            <title>MTU MEMO</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/mtulogo.ico" />
                        </Head>

                        {children}
                    </main>

                </div>

            </div>
            <Footer />
        </div>
    );


}
